# minimal necessary configuration
server:
  servlet:
    context-path: /events-app
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:12:///event-app
